version: '3.1'

services:
  app:
    container_name: auto-service
    image: auto-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/autoservice
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
    volumes:
      - .:/app
    command: sh -c "docker-compose up -d || docker-compose start"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: autoservice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgre.sql:/docker-entrypoint-initdb.d/postgre.sql